porting this plugin base on sf version
EC-CUBE/related-product-plugin pull request #60
Opened 2018-05-22 04:24 UTC by hoand-vn

## 概要(Overview・Refs Issue)
+ Refactor plugin base on sf version

## 方針(Policy)
+ このPullRequestを作るにあたって考慮したものや除外した内容
   - difficult to xpath when change GUI
 
## 実装に関する補足(Appendix)
  - none

2018-07-10 09:04 UTC, ryo-endo commented
管理画面への要素の追加は、TemplateEvent::addSnipetを使用してください。
EC-CUBE#3244

フロントへの要素の追加は、TwigBlockを作成してください。
EC-CUBE#3232
既存のhtmlを変更する必要がある場合は、TemplateEvent::addSnipetを使用してください。

2018-07-10 09:05 UTC, ryo-endo commented on Resource/template/admin/modal_result.twig
> +            {% include "@admin/styleguide_pager.twig" with {'pages': pagination.paginationData, 'routes': 'admin_related_product_search_product_page'} %}
use `@admin/pager.twig`

2018-07-10 09:06 UTC, ryo-endo requested changes
EventSubscriber を使用せずに実装できないでしょうか？

2018-07-12 07:50 UTC, hoand-vn commented
for Travis

2018-07-12 07:50 UTC, closed without merging